---
deployment:
  tasks:
    - export DEPLOYPATH=/home/davidcve/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp/static/css style.css $DEPLOYPATH
    - /bin/cp/static/assets images $DEPLOYPATH
    - /bin/cp/static/js js $DEPLOYPATH
