---
deployment:
  tasks:
    - export DEPLOYPATH=/home/davidcve/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp/css styles.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
